line_loading_limit = 1.0  # 1.0=100%
dt_loading_limit = 1.0    # 1.0=100%
line_safety_margin = 1.5  # 1.1=110%: implies new line added should be rated at least 10% above the DTs actual overloading
xfmr_safety_margin = 1.5  # 1.1=110%: implies new DT added should be rated at least 10% above DT's actual overloading
nominal_voltage = 120
max_iterations = 20
create_upgrade_plots = false
tps_to_test = [0.2, 1.8, 0.1, 0.9] # [min load multiplier without PV, max load multiplier without PV, min load multiplier with PV, max load multiplier with PV]
create_upgrades_library = true     # Can be set to False if we use an externally generated library
upgrade_library_path = ""