target_v = 1
initial_voltage_upper_limit = 1.0583
initial_voltage_lower_limit = 0.9167
final_voltage_upper_limit = 1.05
final_voltage_lower_limit = 0.95
nominal_voltage = 120
nominal_pu_voltage = 1
tps_to_test = [0.2, 1.3, 0.1, 0.9]  # [min load multiplier without PV, max load multiplier without PV, min load multiplier with PV, max load multiplier with PV]
create_topology_plots = false       # Set this to true only if coordinates for all buses in the network are available
cap_sweep_voltage_gap = 1           # This value determines difference increase between cap ON and OFF voltage setting, example (119.5, 120.5), (119,121) and so on
reg_control_bands = [1, 2]          # Reg control voltage bands within which taps will not change
reg_v_delta = 0.5                   # Reg control voltage set point is varied in this range
max_regulators = 4                  # This number gives the maximum number of regulators placed in the feeder apart from substation LTC
use_ltc_placement = true
thermal_scenario_name = "ThermalUpgrade"
