[thermal_upgrade_params]
transformer_upper_limit = 1.25
line_upper_limit = 1.25
line_design_pu = 0.75
transformer_design_pu = 0.75
voltage_upper_limit = 1.05
voltage_lower_limit = 0.95
read_external_catalog = false
external_catalog = ""

[voltage_upgrade_params]
initial_upper_limit = 1.05
initial_lower_limit = 0.95
final_upper_limit = 1.05
final_lower_limit = 0.95
nominal_voltage = 120

[upgrade_simulation_params]
enable_pydss_controller = true

[upgrade_simulation_params.pydss_controller]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = 1
pfMin = 0.8
pfMax = 1
Pmin = 0
Pmax = 1
uMin = 0.9399999999999999
uDbMin = 0.97
uDbMax = 1.03
uMax = 1.06
QlimPU = 0.44
PFlim = 0.9
enable_pf_limit = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
percent_p_cutin = 10
percent_p_cutout = 10
Efficiency = 100
Priority = "Var"
DampCoef = 0.8
