[Reports]
Format = "h5"
Granularity = "per_element_per_time_point"

[[Reports.Types]]
name = "Capacitor State Change Counts"
enabled = true

[[Reports.Types]]
name = "Feeder Losses"
enabled = true

[[Reports.Types]]
name = "PV Clipping"
enabled = false
diff_tolerance_percent_pmpp = 1.0
denominator_tolerance_percent_pmpp = 1.0

[[Reports.Types]]
name = "PV Curtailment"
enabled = false
diff_tolerance_percent_pmpp = 1.0
denominator_tolerance_percent_pmpp = 1.0

[[Reports.Types]]
name = "RegControl Tap Number Change Counts"
enabled = true

[[Reports.Types]]
name = "Thermal Metrics"
enabled = true
transformer_loading_percent_threshold = 150
transformer_window_size_hours = 2
transformer_loading_percent_moving_average_threshold = 120
line_window_size_hours = 1
line_loading_percent_threshold = 150
line_loading_percent_moving_average_threshold = 120

[[Reports.Types]]
name = "Voltage Metrics"
enabled = true
window_size_minutes = 60
range_a_limits = [0.95, 1.05]
range_b_limits = [0.90, 1.0583]
