[voltage]
min_voltage = 0.95
max_voltage = 1.05
num_nodes_any_outside_ansi_b = 350
num_time_points_with_ansi_b_violations = 350

[thermal]
line_max_instantaneous_loading_pct = 150
line_max_moving_average_loading_pct = 120
line_num_time_points_with_instantaneous_violations = 350
line_num_time_points_with_moving_average_violations = 350
transformer_max_instantaneous_loading_pct = 150
transformer_max_moving_average_loading_pct = 120
transformer_num_time_points_with_instantaneous_violations = 350
transformer_num_time_points_with_moving_average_violations = 350
