[voltage]
min_voltage = 0.95
max_voltage = 1.05
num_nodes_any_outside_ansi_b = 0
num_time_points_with_ansi_b_violations = 0

[thermal]
line_num_time_points_with_instantaneous_violations = 0
line_num_time_points_with_moving_average_violations = 0
transformer_num_time_points_with_instantaneous_violations = 0
transformer_num_time_points_with_moving_average_violations = 0
