name: Documentation

on:
  push:
    branches: [main]

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: select python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install NREL-jade
          python -m pip install '.[dev]'
          jade extensions register `python -c "import os,disco;print(os.path.dirname(disco.__path__[0]))"`/disco/extensions/jade_extensions.json
          python -m pip install sphinx
          python -m pip install sphinx_rtd_theme
      - name: build documentation
        run: |
          cd docs
          make clean
          make html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
